
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { User, UserPlan, UserLevel, Campaign, TaskType } from '../types';

const SUPABASE_URL = 'https://moydygbmqzqztpocpniw.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_AHjmsdUChb3TcwHiLUZxlg_oVT45vyN';

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

export const SETUP_SQL = `
-- Tabelas estruturais
CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    "instagramUsername" TEXT NOT NULL,
    points INTEGER DEFAULT 200,
    "dailyPointsEarned" INTEGER DEFAULT 0,
    plan TEXT NOT NULL DEFAULT 'FREE',
    level TEXT NOT NULL DEFAULT 'BRONZE',
    avatar TEXT,
    "isCreator" BOOLEAN DEFAULT true,
    "referredBy" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.campaigns (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    "targetUrl" TEXT NOT NULL,
    "targetQuantity" INTEGER NOT NULL,
    "currentQuantity" INTEGER DEFAULT 0,
    "pointsInvested" INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.completed_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE,
    task_id TEXT REFERENCES public.campaigns(id) ON DELETE CASCADE,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, task_id)
);

-- Políticas RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.completed_tasks ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Profiles') THEN
        CREATE POLICY "Public Access Profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Campaigns') THEN
        CREATE POLICY "Public Access Campaigns" ON public.campaigns FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Tasks') THEN
        CREATE POLICY "Public Access Tasks" ON public.completed_tasks FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
`;

export const DatabaseService = {
  async getUser(userId: string): Promise<User | null> {
    const { data, error } = await supabase.from('profiles').select('*').eq('id', userId).maybeSingle();
    return error ? null : (data as User);
  },

  async createUser(userData: User): Promise<User> {
    const { data, error } = await supabase.from('profiles').insert([userData]).select().single();
    if (error) throw error;
    return data as User;
  },

  async updateUser(userId: string, update: Partial<User>): Promise<User> {
    const { data, error } = await supabase.from('profiles').update(update).eq('id', userId).select().single();
    if (error) throw error;
    return data as User;
  },

    async createCheckoutSession(userId: string, priceId: string, type: string): Promise<string> {
    try {
      const { data } = await supabase.functions.invoke('create-stripe-session', {
        body: { userId, priceId, type }
      });
      if (data?.url) return data.url;
    } catch (e) {
      console.warn("Invoke failed, using fallback URL");
    }
    
    const successUrl = `${window.location.origin}/dashboard?payment=success&type=${type}&val=${priceId}`;
    return `https://buy.stripe.com/test_demo_link?client_reference_id=${userId}&success_url=${encodeURIComponent(successUrl)}`;
  },

  async addCampaign(userId: string, campaign: Campaign): Promise<{ user: User; campaigns: Campaign[] }> {
    const { error: campError } = await supabase.from('campaigns').insert([{ 
      id: campaign.id,
      user_id: userId,
      type: campaign.type,
      targetUrl: campaign.targetUrl,
      targetQuantity: campaign.targetQuantity,
      currentQuantity: campaign.currentQuantity,
      pointsInvested: campaign.pointsInvested,
      status: campaign.status
    }]);

    if (campError) throw campError;

    const user = await this.getUser(userId);
    if (!user) throw new Error("User not found");

    const updatedUser = await this.updateUser(userId, { 
      points: Math.max(0, (user.points || 0) - campaign.pointsInvested)
    });

    const campaigns = await this.getCampaigns(userId);
    return { user: updatedUser, campaigns };
  },

  async getCampaigns(userId: string): Promise<Campaign[]> {
    const { data, error } = await supabase.from('campaigns').select('*').eq('user_id', userId).order('created_at', { ascending: false });
    return error ? [] : (data as Campaign[]);
  },

  async getAvailableTasks(userId: string): Promise<Campaign[]> {
    const { data: completed } = await supabase.from('completed_tasks').select('task_id').eq('user_id', userId);
    const completedIds = completed?.map(c => c.task_id) || [];

    let query = supabase.from('campaigns').select('*').neq('user_id', userId).eq('status', 'ACTIVE');
    if (completedIds.length > 0) query = query.not('id', 'in', `(${completedIds.join(',')})`);

    const { data, error } = await query;
    return error ? [] : (data as Campaign[]).filter(c => c.currentQuantity < c.targetQuantity);
  },

  async completeTask(userId: string, campaignId: string, pointsValue: number): Promise<User> {
    const { error: taskError } = await supabase.from('completed_tasks').insert([{ user_id: userId, task_id: campaignId }]);
    if (taskError) throw new Error("Ação já registrada.");

    const { data: campaign } = await supabase.from('campaigns').select('*').eq('id', campaignId).single();
    if (campaign) {
      const newQty = (campaign.currentQuantity || 0) + 1;
      await supabase.from('campaigns').update({ 
        currentQuantity: newQty,
        status: newQty >= campaign.targetQuantity ? 'COMPLETED' : 'ACTIVE'
      }).eq('id', campaignId);
    }

    const user = await this.getUser(userId);
    if (!user) throw new Error("User not found");

    return await this.updateUser(userId, {
      points: (user.points || 0) + pointsValue,
      dailyPointsEarned: (user.dailyPointsEarned || 0) + pointsValue
    });
  },

  async processPurchase(userId: string, type: 'PLAN' | 'POINTS' | 'BOOST', value: any): Promise<User> {
    const user = await this.getUser(userId);
    if (!user) throw new Error("User not found");
    
    let update: Partial<User> = {};
    if (type === 'PLAN') update = { plan: value as UserPlan };
    else if (type === 'POINTS') update = { points: (user.points || 0) + Number(value) };
    else if (type === 'BOOST') update = { level: UserLevel.DIAMANTE };
    
    return await this.updateUser(userId, update);
  }
};
